-- MySQL Script generated by MySQL Workbench
-- Tue Aug 22 10:50:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vstp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vstp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vstp` DEFAULT CHARACTER SET utf8 ;
USE `vstp` ;

-- -----------------------------------------------------
-- Table `vstp`.`Benutzer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vstp`.`Benutzer` (
  `name` VARCHAR(12) NOT NULL,
  `passwort` VARCHAR(45) NULL,
  `sachbearbeiter` TINYINT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vstp`.`Veranstaltung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vstp`.`Veranstaltung` (
  `idVeranstaltung` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `beschreibung` LONGTEXT NULL,
  `start` DATETIME NULL,
  `ende` DATETIME NULL,
  `teilnehmer` INT NULL,
  `maxTeilnehmer` INT NULL,
  `projektverantwortlicher` VARCHAR(45) NULL,
  PRIMARY KEY (`idVeranstaltung`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vstp`.`BenutzerProVeranstaltung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vstp`.`BenutzerProVeranstaltung` (
  `veranstaltungsId` INT NOT NULL,
  `name` VARCHAR(12) NOT NULL,
  `prioritaet` INT NULL DEFAULT 0,
  `eintragungszeitpunkt` DATETIME NULL,
  `bestaetigt` TINYINT NULL,
  PRIMARY KEY (`veranstaltungsId`, `name`),
  INDEX `fk_BenutzerProVeranstaltung_Veranstaltung_idx` (`veranstaltungsId` ASC),
  INDEX `fk_BenutzerProVeranstaltung_Benutzer1_idx` (`name` ASC),
  CONSTRAINT `fk_BenutzerProVeranstaltung_Veranstaltung`
    FOREIGN KEY (`veranstaltungsId`)
    REFERENCES `vstp`.`Veranstaltung` (`idVeranstaltung`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BenutzerProVeranstaltung_Benutzer1`
    FOREIGN KEY (`name`)
    REFERENCES `vstp`.`Benutzer` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vstp`.`Systemeinstellung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vstp`.`Systemeinstellung` (
  `key` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`key`))
ENGINE = InnoDB;

CREATE USER 'Admin';

GRANT ALL ON `vstp`.* TO 'Admin';
CREATE USER 'Sachbearbeiter';

GRANT SELECT, INSERT, TRIGGER ON TABLE `vstp`.* TO 'Sachbearbeiter';
CREATE USER 'Mitarbeiter';

GRANT SELECT ON TABLE `vstp`.* TO 'Mitarbeiter';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `vstp`.* TO 'Mitarbeiter';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
